spring:
  datasource:
    url: ${MYSQL_CONNECT_STRING:jdbc:mysql://localhost/rpgzada?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    show-sql: true